spring:
  profiles:
    active: dev
#server:
#  port: 8088
#  servlet:
#    context-path: /luckymoney
#
#limit:
#  minMoney: 0.21
#  maxMoney: 999
#  description: 最少发${limit.minMoney}元, 最多发${limit.maxMoney}