server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.21
  maxMoney: 999
  description: 最少发${limit.minMoney}元, 最多发${limit.maxMoney}

spring:
  main:
    lazy-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-boot
    username: postgres
    password: postgres
  jpa:
    show-sql: true #显示执行sql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true # 生成hibernate对db操作的执行统计
        jdbc:
          batch_size: 2 #批量操作条数
          batch_versioned_date: true #
        order_inserts: true #执行批量插入操作的时候按照实体类进行分组
        order_updates: true #
